const GET_CHARACTERS = "GET_CHARACTERS";
const CHANGE_FILTER = "CHANGE_FILTER";
const GET_TOTAL_PAGES = "GET_TOTAL_PAGES";
const UPDATE_SEARCH_NAME = "UPDATE_SEARCH_NAME";
const GET_CHARACTER = "GET_CHARACTER";

export default {
  CHANGE_FILTER,
  GET_CHARACTERS,
  GET_TOTAL_PAGES,
  UPDATE_SEARCH_NAME,
  GET_CHARACTER,
};
