const GET_CHARACTERS = "GET_CHARACTERS";
const CHANGE_FILTER = "CHANGE_FILTER";
const GET_TOTAL_PAGES = "GET_TOTAL_PAGES";
const UPDATE_SEARCH_NAME = "UPDATE_SEARCH_NAME";
const GET_CHARACTER = "GET_CHARACTER";
const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";
const GET_FAVOURITE_LIST = "GET_FAVOURITE_LIST";

export default {
  CHANGE_FILTER,
  GET_CHARACTERS,
  GET_TOTAL_PAGES,
  UPDATE_SEARCH_NAME,
  GET_CHARACTER,
  ADD_TO_FAVOURITE,
  REMOVE_FROM_FAVOURITE,
  GET_FAVOURITE_LIST,
};
