const SET_CHARACTERS = "SET_CHARACTERS";
const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";
const UPDATE_CURRENT_FILTER = "UPDATE_CURRENT_FILTER";
const SET_SEARCH_NAME = "SET_SEARCH_NAME";
const SET_CHARACTER = "SET_CHARACTER";

export default {
  SET_CHARACTERS,
  SET_TOTAL_PAGES,
  UPDATE_CURRENT_FILTER,
  SET_SEARCH_NAME,
  SET_CHARACTER,
};
