const UPDATE_CHARACTERS = "UPDATE_CHARACTERS";
const UPDATE_TOTAL_PAGES = "UPDATE_TOTAL_PAGES";
const UPDATE_CURRENT_FILTER = "UPDATE_CURRENT_FILTER";
const SET_START_PAGE = "SET_START_PAGE";
const SET_SEARCH_NAME = "SET_SEARCH_NAME";

export default {
  UPDATE_CHARACTERS,
  UPDATE_TOTAL_PAGES,
  UPDATE_CURRENT_FILTER,
  SET_START_PAGE,
  SET_SEARCH_NAME,
};
